### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by anggijaya** [PacktPublishing/TensorFlow-Machine-Learning-Projects#5]
Hi,

## when I ran this code:

mnist=MNIST()
x_train,y_train,x_test,y_test=mnist.load_data()

mnist.y_onehot = True
mnist.x_layout = imutil.LAYOUT_NP
x_test = mnist.load_images(x_test)
y_test = nputil.onehot(y_test)

print('Loaded x and y')
print('Train: x:{}, y:{}'.format(len(x_train),y_train.shape))
print('Test: x:{}, y:{}'.format(x_test.shape,y_test.shape))

## I got a message or an error like this:

Already exists: C:\Users\User\datasets\mnist\train-images-idx3-ubyte.gz
Already exists: C:\Users\User\datasets\mnist\train-labels-idx1-ubyte.gz
Already exists: C:\Users\User\datasets\mnist\t10k-images-idx3-ubyte.gz
Already exists: C:\Users\User\datasets\mnist\t10k-labels-idx1-ubyte.gz
Extracting and rearchiving as jpg files...
C:\Users\User\datasets\mnist\train-images-idx3-ubyte.gz
Reading from  C:\Users\User\datasets\mnist\train-images-idx3-ubyte.gz
Reading from  C:\Users\User\datasets\mnist\train-labels-idx1-ubyte.gz
Saving  train

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-271cad49155b> in <module>
      3 # prepare x and y data
      4 
----> 5 x_train,y_train,x_test,y_test=mnist.load_data()
      6 
      7 mnist.y_onehot = True

F:\Satria\03. Python\01. Deep Learning\5. Tensorflow_Machine_Learning_Projects_9781789132212\datasetslib\datasetslib\mnist.py in load_data(self, force, shuffle, x_is_images, x_layout)
     89                 image_path = os.path.join(tt_folder,str(labels[i]),'{}.jpg'.format(i))
     90                 if not os.path.isfile(image_path):
---> 91                     cv2.imwrite(image_path, data[i][:,:,0])
     92                     modified_files = True
     93 

IndexError: too many indices for array

How to solve this error?
Thanks

**Comment by shubham763** [comment]
Please reopen the issue if it still exists.
